---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-manager
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      serviceAccountName: longhorn-service-account
      containers:
      - name: manager
        image: longhornio/longhorn-manager:v1.4.2
        imagePullPolicy: IfNotPresent
        args:
        - manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 9500
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-engine
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-engine
  template:
    metadata:
      labels:
        app: longhorn-engine
    spec:
      serviceAccountName: longhorn-service-account
      containers:
      - name: engine
        image: longhornio/longhorn-engine:v1.4.2
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: var-lib-longhorn
          mountPath: /var/lib/longhorn
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: var-lib-longhorn
        hostPath:
          path: /var/lib/longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  type: ClusterIP
  selector:
    app: longhorn-manager
  ports:
  - port: 9500
    targetPort: 9500
